Since there is no complete file available online that corresponds all the precincts with zip codes in NYC, we need to do mannually do some data preprocessing.

In [1]:
%matplotlib inline
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import math
import itertools

In [3]:
df = pd.read_csv('/Users/YuchenZheng/Desktop/poverty.tsv',sep='\t')

In [4]:
del df['#'], df['National Rank']

In [5]:
df['City'] = df.City.astype(str)

In [6]:
df.head()

,Zip Code,Location,City,Population,% Poverty Level
0,10165,"40.752131, -73.978722","New York, New York",7,100.00 %
1,10048,"40.711665, -74.012417","New York, New York",55,82.75 %
2,10474,"40.810203, -73.884437","Bronx, New York","11,354",70.12 %
3,10454,"40.805528, -73.916632","Bronx, New York","34,976",70.01 %
4,14605,"43.168307, -77.601608","Rochester, New York","14,418",69.28 %

In [7]:
df['City'] = df.apply(lambda x : str(x[2]).split(',')[0],1)

In [3]:
df1 = pd.read_csv('/Users/YuchenZheng/Desktop/Data Science/Data Mining/final project/zipcodes.tsv',sep='\t')

In [4]:
df1.head()

  Borough                Neighborhood                   ZIP_codes
0   Bronx               Central Bronx         10453, 10457, 10460
1   Bronx      Bronx Park and Fordham         10458, 10467, 10468
2   Bronx  High Bridge and Morrisania         10451, 10452, 10456
3   Bronx  Hunts Point and Mott Haven  10454, 10455, 10459, 10474
4   Bronx   Kingsbridge and Riverdale                10463, 10471

In [5]:
df1['ZIP_codes']=df1.ZIP_codes.astype(str)

In [6]:
a = df1.ZIP_codes.str.split(',')
a = [x.strip() for x in sum(a,[])]
a = list(set(a))

In [7]:
a[:5]

['11417', '11222', '11429', '11224', '11223']

In [8]:
zips = []
for index, row in df1.iterrows():
    #print(index,row)
    zips.append(row[2].split(','))

In [9]:
zips = list(itertools.chain.from_iterable(zips))

In [11]:
zipcode = []
for stuff in zips:
    stuff.strip()
    #print stuff.strip()
    zipcode.append(stuff.strip())

In [12]:
for stuff in df['Zip Code']:
    #print stuff
    if str(stuff) in zipcode:
        continue
    else:
        df = df[df['Zip Code'] != stuff]

NameError: name 'df' is not defined

In [629]:
df

,Zip Code,Location,City,Population,% Poverty Level
2,10474,"40.810203, -73.884437",Bronx,"11,354",70.12 %
3,10454,"40.805528, -73.916632",Bronx,"34,976",70.01 %
9,10456,"40.830877, -73.907954",Bronx,"76,656",64.49 %
10,10459,"40.825558, -73.893156",Bronx,"39,080",64.43 %
11,10457,"40.846687, -73.898374",Bronx,"69,048",60.93 %
13,10452,"40.837763, -73.923314",Bronx,"72,138",60.47 %
15,10453,"40.852779, -73.912332",Bronx,"76,775",59.12 %
16,11211,"40.713507, -73.952578",Brooklyn,"85,089",58.80 %
18,10455,"40.814678, -73.908333",Bronx,"37,465",57.49 %
19,10460,"40.842724, -73.879745",Bronx,"53,707",56.96 %
20,10035,"40.795487, -73.929501",New York,"32,702",56.06 %
21,11206,"40.702037, -73.942444",Brooklyn,"69,032",55.87 %
26,10039,"40.826296, -73.937053",New York,"21,737",54.40 %
27,10030,"40.818492, -73.943283",New York,"25,847",53.98 %
28,11212,"40.662907, -73.912969",Brooklyn,"85,161",53.88 %
29,10458,"40.862831, -73.886395",Bronx,"77,840",53.86 %
30,11237,"40.704160, -73.921139",Brooklyn,"48,910",53.85 %
32,10451,"40.822092, -73.922612",Bronx,"40,961",52.49 %
33,11233,"40.678089, -73.919867",Brooklyn,"61,955",52.02 %
34,11207,"40.670361, -73.893848",Brooklyn,"86,551",50.89 %
35,11221,"40.691310, -73.927772",Brooklyn,"76,363",50.67 %
39,10468,"40.868093, -73.899730",Bronx,"78,309",48.84 %
41,10472,"40.829650, -73.869368",Bronx,"64,867",48.52 %
44,10029,"40.792245, -73.945230",New York,"75,390",46.08 %
45,11219,"40.632769, -73.996642",Brooklyn,"85,987",45.44 %
46,10026,"40.802320, -73.952943",New York,"30,377",45.26 %
49,11205,"40.696771, -73.967061",Brooklyn,"35,622",44.53 %
51,11208,"40.669598, -73.871270",Brooklyn,"87,165",44.37 %
52,10031,"40.825857, -73.949451",New York,"60,221",43.83 %
53,10032,"40.839194, -73.942591",New York,"63,842",40.82 %
...,...,...,...,...,...
954,10024,"40.786307, -73.970694",New York,"61,414",9.19 %
973,11361,"40.764370, -73.771869",Bayside,"29,206",8.95 %
989,11413,"40.669293, -73.750553",Springfield Gardens,"39,827",8.76 %
1008,11427,"40.729722, -73.749800",Queens Village,"23,014",8.61 %
1038,10314,"40.598825, -74.163336",Staten Island,"84,821",8.24 %
1064,10023,"40.775394, -73.982197",New York,"62,206",7.99 %
1071,11414,"40.658217, -73.844820",Howard Beach,"28,121",7.90 %
1072,11411,"40.694307, -73.735948",Cambria Heights,"21,282",7.90 %
1076,11426,"40.736619, -73.723610",Bellerose,"18,727",7.89 %
1080,10017,"40.752292, -73.972393",New York,"16,201",7.86 %
1086,10471,"40.898117, -73.900227",Bronx,"23,413",7.78 %
1091,11357,"40.786415, -73.810924",Whitestone,"39,491",7.72 %
1122,11364,"40.745620, -73.757537",Oakland Gardens,"34,539",7.42 %
1127,11366,"40.727929, -73.793074",Fresh Meadows,"13,366",7.35 %
1145,11004,"40.745809, -73.711240",Glen Oaks,"14,682",7.08 %
1149,10309,"40.530847, -74.221178",Staten Island,"27,207",7.02 %
1180,10308,"40.551236, -74.150961",Staten Island,"26,451",6.74 %
1193,11697,"40.555681, -73.920688",Breezy Point,"4,226",6.57 %
1197,11360,"40.782352, -73.780749",Bayside,"19,350",6.54 %
1202,10014,"40.733471, -74.007098",New York,"32,667",6.50 %
1206,10280,"40.708501, -74.016828",New York,"6,614",6.47 %
1268,10028,"40.776865, -73.954721",New York,"44,987",5.73 %
1270,10021,"40.769742, -73.961653",New York,"102,078",5.72 %
1304,10307,"40.506815, -74.241709",Staten Island,"11,669",5.25 %
1308,10022,"40.758615, -73.967752",New York,"30,642",5.24 %
1335,10312,"40.547291, -74.179264",Staten Island,"58,867",4.96 %
1349,11005,"40.756578, -73.714178",Floral Park,"2,195",4.77 %
1350,10464,"40.867099, -73.797609",Bronx,"4,634",4.76 %
1408,10007,"40.713973, -74.008336",New York,"3,522",4.19 %
1459,11363,"40.772591, -73.746472",Little Neck,"6,917",3.73 %